image:
  name: registry.videolan.org/vlc-debian-wasm-emscripten:20220505193036
  entrypoint: [] # See issue : https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1170

stages:
  - build

compile-job:
  stage: build
  tags:
    - docker
    - amd64
  script:
    - bash compile.sh              # Compilation

  only:
    - incoming
  artifacts:
    paths:                  ## PATHS FOR ARTIFACTS
      - experimental*       # worker.js, wasm file and js file, data...
      - assets/             # Assets for logos etc...
      - vlc.html            # HTML page
      - vlc_media_list_poc.html
      - lib/*               # libvlc.js, module-loader.js, overlay.js, wasm-imports.js
      - ./vlc/modules/gui/qt/pixmaps/toolbar/volume-muted.png
      - ./vlc/modules/gui/qt/pixmaps/pause.png
      - ./vlc/modules/gui/qt/pixmaps/toolbar/volume-medium.png
      - ./vlc/modules/gui/qt/pixmaps/play.png
      - ./vlc/modules/gui/qt/pixmaps/play_button.svg
      - ./vlc/modules/audio_output/webaudio/audio-worklet-processor.js
    expire_in: 1 week       # Expiration date
